version: "3"

services:
  {{cookiecutter.project_dir}}-api:
    build:
      context: {{cookiecutter.module_name}}_api
    ports:
      - "8080:8080"
  {{cookiecutter.project_dir}}-ui:
    build:
      context: react-app
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - {{cookiecutter.project_dir}}-api
    links:
      - {{cookiecutter.project_dir}}-api
