version: "3.9"

services:
  {{cookiecutter.project_dir}}-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DJANGO_SECRET_KEY=d0ckerC0mp0seRun
      - DJANGO_ALLOWED_HOSTS=localhost
    {{cookiecutter.project_dir}}-ui:
    build:
      context: apps/ui
    environment:
      - API_HOST={{cookiecutter.project_dir}}-api:8080
    ports:
      - "80:80"
    depends_on:
      - {{cookiecutter.project_dir}}-api
    links:
      - {{cookiecutter.project_dir}}-api
