# Default values for {{cookiecutter.project_name}}-etl.
# This is a YAML-formatted file.
# Add annotations to the pods
podAnnotations: {}
# Add labels to the pods
podsLabels: {}

image:
  repository: draft
  tag: dev
  pullPolicy: Always

# optional list of image pull secrets to use to pull images
jx:
  # optional image pull secrets
  imagePullSecrets: []

  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# define environment variables here as a map of key: value
extraEnv:
  - name: API_URL
    value:

cronjob:
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 0
  successfulJobsHistoryLimit: 0

serviceAccount:
  enabled: false
  name: ""
  annotations: {}
  labels: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
